// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Models;

namespace eCommerce.Migrations
{
    [DbContext(typeof(ecommerceContext))]
    [Migration("20220313081708_correctProject")]
    partial class correctProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("eCommerce.Models.Variant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ProductVariantproductId")
                        .HasColumnType("int");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matrial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductVariantproductId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("eCommerce.Models.language", b =>
                {
                    b.Property<int>("languageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("nameLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("languageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("eCommerce.Models.languageWord", b =>
                {
                    b.Property<int>("languageWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Defaultword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("languageId")
                        .HasColumnType("int");

                    b.Property<string>("word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("languageWordId");

                    b.HasIndex("languageId");

                    b.ToTable("LanguageWords");
                });

            modelBuilder.Entity("eCommerce.Models.product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("eCommerce.Models.variantValue", b =>
                {
                    b.Property<int>("variantValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("value")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("variantValueId");

                    b.ToTable("VariantValues");
                });

            modelBuilder.Entity("eCommerce.Models.Variant", b =>
                {
                    b.HasOne("eCommerce.Models.product", "ProductVariant")
                        .WithMany("productVariant")
                        .HasForeignKey("ProductVariantproductId");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("eCommerce.Models.languageWord", b =>
                {
                    b.HasOne("eCommerce.Models.language", "Language")
                        .WithMany("words")
                        .HasForeignKey("languageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("eCommerce.Models.language", b =>
                {
                    b.Navigation("words");
                });

            modelBuilder.Entity("eCommerce.Models.product", b =>
                {
                    b.Navigation("productVariant");
                });
#pragma warning restore 612, 618
        }
    }
}
